trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: "Build Application"
    jobs:
      - template: templates/build.yml

  - stage: SAST
    displayName: "Static Code Analysis"
    dependsOn: Build
    jobs:
      - template: templates/sast.yml

  - stage: Release
    displayName: "Publish Artifact"
    dependsOn: SAST
    jobs:
      - template: templates/release.yml

  - stage: Deploy
    displayName: "Deploy to Environment"
    dependsOn: Release
    condition: eq(variables['Build.SourceBranchName'], 'main')
    jobs:
      - template: templates/deploy.yml