trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - script: |
      az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)

  - script: |
      docker build -t wjpcregistry.azurecr.io/wjpc-image:latest .
      docker login wjpcregistry.azurecr.io -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET)
      docker push wjpcregistry.azurecr.io/wjpc-image:latest
