jobs:
  - job: Build
    displayName: "Build Application using Docker Compose"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - script: |
          docker-compose -f docker-compose.yml run builder
        displayName: "Compile Application with Docker Compose"

      - script: |
          docker-compose -f docker-compose.yml build spring-boot-app
        displayName: "Build Spring Boot Docker Image"
