jobs:
  - job: SAST
    displayName: "Static Analysis with SonarQube"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: SonarQubePrepare@5
        inputs:
          SonarQube: 'SonarQubeServiceConnection'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'spring-boot-app'
          cliProjectVersion: '1.0'
      - script: |
          mvn sonar:sonar
        displayName: "Run SonarQube Analysis"
      - task: SonarQubePublish@5
        inputs:
          pollingTimeoutSec: '300'
